apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jnh7wf0kj-go-gitops
  description: This is GitOps manifest for jnh7wf0kj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jnh7wf0kj-go
    janus-idp.io/tekton: jnh7wf0kj-go
    backstage.io/kubernetes-id: jnh7wf0kj-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jnh7wf0kj-go
