apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jnh7wf0kj-go
  janus-idp.io/tekton: jnh7wf0kj-go
  backstage.io/kubernetes-id: jnh7wf0kj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jnh7wf0kj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
