apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jnh7wf0kj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jnh7wf0kj-go 
  name: jnh7wf0kj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jnh7wf0kj-go 
